// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Confirm():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectory():Promise<string>;

export function ReadDirectory(arg1:string):Promise<string>;
