// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create_file(arg1:number,arg2:number):Promise<number>;

export function Create_folder(arg1:string):Promise<string>;

export function Delete_file(arg1:number,arg2:number):Promise<number>;

export function Delete_folder(arg1:number,arg2:number):Promise<number>;

export function OverWrite_file(arg1:number,arg2:number):Promise<number>;

export function OverWrite_folder(arg1:number,arg2:number):Promise<number>;

export function Read_file(arg1:number,arg2:number):Promise<number>;

export function Read_folder(arg1:number,arg2:number):Promise<number>;
