// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create_file(arg1, arg2) {
  return window['go']['main']['CRUD']['Create_file'](arg1, arg2);
}

export function Create_folder(arg1) {
  return window['go']['main']['CRUD']['Create_folder'](arg1);
}

export function Delete_file(arg1, arg2) {
  return window['go']['main']['CRUD']['Delete_file'](arg1, arg2);
}

export function Delete_folder(arg1, arg2) {
  return window['go']['main']['CRUD']['Delete_folder'](arg1, arg2);
}

export function OverWrite_file(arg1, arg2) {
  return window['go']['main']['CRUD']['OverWrite_file'](arg1, arg2);
}

export function OverWrite_folder(arg1, arg2) {
  return window['go']['main']['CRUD']['OverWrite_folder'](arg1, arg2);
}

export function Read_file(arg1, arg2) {
  return window['go']['main']['CRUD']['Read_file'](arg1, arg2);
}

export function Read_folder(arg1, arg2) {
  return window['go']['main']['CRUD']['Read_folder'](arg1, arg2);
}
